### ISSUE TITLE
Service Bind

### ISSUE THREAD

**Issue by koljamaier** [fraunhoferfokus/peer-upnp#15]
Hi,

I appreciate your work. Right now I'm beginning to understand the internals.
Sadly I can not follow the snippet (in [binary-light-client.js](https://github.com/fraunhoferfokus/peer-upnp/blob/master/test/binary-light-client.js)):

```javascript
service.bind(function(service){
            // Call UPnP interface SetTarget of SwitchPower Service
            console.log("Turn light ON using SetTarget with input parameter NewTargetValue=1");
			service.SetTarget({
				NewTargetValue: 1
			},function(res){
				console.log("SetTarget done");
			});
		}).on("event",function(data){
			console.log("Receive update from SwitchPower Service 1: ",data);
		});
```
Particularly I am having problems with `.bind`.

I understand `bind` in toy examples, like:
```javascript
var sum = function(a, b) {
  return a + b;
};

var add5 = sum.bind(null, 5);
console.log(add5(10));
```
As a way of binding a functions context. 

Even after reading  your comments:
```
 // bind to the service in order to call its methods
 // bind will generate a JavaScript function for each service method.
 // Inputs and outputs are JSON objects where the keys are the name of the
 // inputs or outputs.
```
there are many question marks left in my head.

I would very much appreciate any help as this seems to be a fun project to work on!

Cheers

**Comment by aldafu** [comment]
This is not the JavaScript ```bind``` function you're thinking of, but rather another function with the same name defined entirely by the project. It is necessary to call this function prior to any interaction with the service you want to use. You "bind to the service" to establish a connection that makes it useable.
