### ISSUE TITLE
Readme.md violates GNU Lesser General Public License v3.0

### ISSUE THREAD

**Issue by kymahi** [fraunhoferfokus/peer-upnp#24]
From the README:

> Free for non commercial use released under the GNU Lesser General Public License v3.0, See LICENSE file.

This contradicts and violates the LGPL v3.0.

You must allow this library not only to be used in commercial, but proprietary software as well, per [GNU Licenses FAQ](https://www.gnu.org/licenses/gpl-faq.html#NoMilitary).

**Comment by louaybassbouss** [comment]
Thanks @kymahi now is fixed. I will close this issue
